alias ls='ls --color=auto'
alias l='ls --color=auto -1tr'
alias grep='grep --color=auto'
alias startx='/usr/bin/startx & disown; exit'
alias g='git pull && git add . && git add -u . && git commit && git push'
alias a='time ansible-playbook'
