pulseaudio --start
xrandr --output LVDS-1 --off
if test 12 -eq $(date +%m); then
  # Merry Christmas.
  mplayer -loop 0 -rootwin -volume 0 .christmas_video.mp4
else
  xscreensaver -nosplash
fi &
exec i3
