#!/bin/bash

### BEGIN INIT INFO
# Provides:          pulseaudio
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start pulseaudio at boot time
# Description:       Enable pulseaudio.
### END INIT INFO


action="${1}"
pid_file=/var/run/pulseaudio.pid


function start {
  echo -n "Starting..."
  # If PID file exists
  if test -e $pid_file; then
    pid=$(< $pid_file)
    # If PID is running
    if ps -p $pid >/dev/null 2>&1; then
      echo "Error:  pulseaudio already started with pid:  ${pid}"
      return 1
    fi
    echo "Warning:  ${pid_file} exists, but PID ${pid} is not running."
  fi

  nohup pulseaudio --system >/var/log/pulseaudio.log 2>&1 &
  pid=$(echo $!)
  echo "${pid}" > $pid_file
  echo "OK"
  return 0
}


function stop {
  echo -n "Stopping..."
  # If PID file exists
  if test -e $pid_file; then
    pid=$(< $pid_file)
    # If PID is running
    if ps -p $pid >/dev/null 2>&1; then
      # If PID is killed
      if kill $pid; then
        rm -f $pid_file
        echo "OK"
        return 0
      fi
      echo "Error:  Failed to kill pid:  ${pid}"
      return 1
    fi
    echo "Warning:  $pid_file exists, but PID ${pid} is not running."
    rm -f $pid_file
  else
    echo "Warning:  pulseaudio does not appear to be started."
    return 0
  fi

}


function status {
  echo -en "Status:  "
  if test -e $pid_file; then
    pid=$(< $pid_file)
    if ps -p $pid >/dev/null 2>&1; then
      echo -e "started with pid:  $pid"
      return 0
    fi
    echo -e "${pid_file} exists, but PID ${pid} is not running."
    return 2
  fi

  echo -e "stopped"
  return 1
}


case "${action}" in
  'start')
    start
    exit $?
    ;;
  'stop')
    stop
    exit $?
    ;;
  'restart')
    if status; then
      stop && start
    else
      start
    fi
    exit $?
    ;;
  'status')
    status
    exit $?
    ;;
  *)
    echo -e "Usage:\n  ${0} {start|stop|restart|status}"
    exit 1;
    ;;
esac

